server:
  port: 23115
  servlet:
    context-path: /tut-clockin

spring:
  profiles:
    active: dev
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    username: mailmye20232560@163.com
    #授权码
    password: AWGDYMUOQAOIIYTJ
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true