# todo：信息是随便写的，自己根据需求更改

server:
  port: 23115

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.115.23:3308/TUT-clockin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: Sipc@MySQL8
  data:
    redis:
      host: 192.168.115.23
      port: 6379
      password:
      database: 6

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sipc.clockin.model.dao
